

trigger:
  branches:
    include: 
    - develop
    - master
  paths:
    include: 
     - /src/*

resources:
  repositories:
  - repository: devops
    type: git
    name: pub/devops
    ref: master


jobs:
- template: dotnet-build-deploy.yml@devops
  parameters:
    versionPrefix: '0.0.1'
    projectName: 'Code2.Data.GeoIP'
    hasUnitTests: true
    createZip: true
    createNugetPackage: true
    internalNugetFeed: 'pub/main1'
    ${{ if eq(variables['Build.SourceBranchName'], 'master' ) }}: 
      createGithubRelease: true